### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by alvaro-32**
First (beta) release  this contains the following features

- Timeline: posts that other users create on the api
- Login: login with a valid user.
- Register: register an user on APINGweb
- Home: landing page

### CODE REVIEW

**Comment by alvaro-32** [comment]
Need to work more on the commits descriptions :disappointed:

**Comment by v1nte** [comment]
> Need to work more on the commits descriptions 😞

He is talking about you @panconpan99 🥇

**Comment by alvaro-32** [comment]
also talk about me, my commits sucks :clown_face:

**Review by v1nte — COMMENTED** [review]
LGTM!

**Review by v1nte — APPROVED** [review]
LGMT!

**Comment by panconpan99** [comment]
我的人民抱怨很多 👍

**Comment by lactunkk** [comment]
さて、私の貢献は.....

**Comment by panconpan99** [comment]
為我的承諾感到自豪 💪 💪

**Pull request merged**
